### PR TITLE
Update links.md

### PR DESCRIPTION
**Pull request by asterwolf**
Definitely a link that should be available on our site. Useful handouts for B13 material, created and proved by Alumni Patrick Hawks!

### CODE REVIEW

**Comment by pathawks** [comment]
Cool 👍 

Would it look better without the hyphens?
Otherwise LGTM :shipit:

**Comment by asterwolf** [comment]
Updated and agreed! I'll leave it up to you to merge when there isn't anything else to change.

**Comment by pathawks** [comment]
Boom. Merged.

**Comment by asterwolf** [comment]
Right on! Thank you Pat!

**Pull request merged**
