### PR TITLE
Format Friday's agenda

### PR DESCRIPTION
**Pull request by pathawks**
This build on @ChadH1971's work in #54, and formats the agenda with nice Markdown lists.

### CODE REVIEW

**Comment by pathawks** [comment]
Preview

**Comment by asterwolf** [comment]
But something went wrong in #54 and so we should just strike it and merge through #54? #54 looks good to me.

**Comment by pathawks** [comment]
@asterwolf This includes the commit from #54, plus some formatting corrections. The problem with #54 is that it is not outputting correct HTML, which breaks the build and prevents merging.

If you want to close this and fix things over there that's fine. If you want to take this branch and build on it, that's fine. Just trying to help.

**Comment by asterwolf** [comment]
We should keep this one and strike #54. I believe it looks good as of this commit, but I'll check with Chad to see what else he wants to change up.

**Comment by ChadH1971** [comment]
I'm good with 55. I will probably use it as a template file once it's merged.

**Comment by asterwolf** [comment]
I'll go ahead and merge it then. Good work guys!

**Pull request merged**
