### PR TITLE
updating minutes

### PR DESCRIPTION
**Pull request by asterwolf**

### CODE REVIEW

**Comment by asterwolf** [comment]
@pathawks , Would you know why its blocking my merge? I believe something is outdated, is that on my end or on the site's end?

**Comment by pathawks** [comment]
Sorry!
Change [this line](https://github.com/AICSC/aicsc.github.io/blob/master/.travis.yml#L3) to 2.3.0
You just need to be using a newer version of Ruby to test.

**Comment by asterwolf** [comment]
Alright, so changing this line shall do the trick? I also updated the newest version of ruby on my computer as well. Thanks again Pat!

**Comment by asterwolf** [comment]
Awesome! I'll merge them up.

**Pull request merged**
