### PR TITLE
New branch

### PR DESCRIPTION
**Pull request by asterwolf**

### CODE REVIEW

**Comment by asterwolf** [comment]
I was just modifying the minutes as they displayed improperly. The problem was with indentation and lack of spaces in between bolded lines. I tested this on my computer and displayed as I believe it should have been to begin with. 

I'm not sure if there is 5 other file changes that came with my pull request? I only mean for the modification of the minutes of 10-07-16.

**Comment by pathawks** [comment]
You weren't on the latest `master` branch when you made the changes.

**Comment by asterwolf** [comment]
Oh!! I must change branches to Master before pulling changes. I tried pulling changes, but probably didn't receive them as I was on my branch newBranch.

**Comment by asterwolf** [comment]
That was exactly it. I just pulled all updates made to master. Thanks Pat!

**Pull request closed without merging**
