### PR TITLE
Create VicePresidentResolution.markdown

### PR DESCRIPTION
**Pull request by ChadH1971**
I should have posted this with a link in the agenda for 9/16. I need to add a link to it in the agenda for October 7th to proceed to 2nd reading. Need to add the link onto the links page and mention it on Slack as well.

### CODE REVIEW

**Comment by pathawks** [comment]
This will not be included in the site.

Anything in the `_posts/` directory must have a filename that conforms to the date + slug format.

**Comment by ChadH1971** [comment]
I wanted to make another folder for it, but I don't have privileges for that

**Comment by pathawks** [comment]
> I wanted to make another folder for it, but I don't have privileges for that.

Git does not have any concept of folders. It just keeps track of filenames and blobs as kind of a key-value store. If you give a file a name that includes `/`, it will appear nested in whatever directory you specify. There is no way to add an empty directory to Git, and there are no special permissions required to nest a file inside an arbitrary directory.

> We need to have a place for things that come up from time to time that are supporting documents for the agenda items.

There is the `pages/` directory, but I agree that it may not be the best place for something like this. Maybe a `supportingDocs/` or similar?

**Comment by ChadH1971** [comment]
supportingDocs/ is a good container and thanks for the reminder about how to create it.

**Pull request closed without merging**
