### PR TITLE
New branch

### PR DESCRIPTION
**Pull request by asterwolf**

### CODE REVIEW

**Comment by pathawks** [comment]
Your PRs always have the most descriptive names 🙄😛

**Comment by asterwolf** [comment]
Is that sarcastic? As in I never put a description? I mean, not like anyone on the board bothers to review things around here, yet alone read the description lol. It's a ghost town around here. *cries*

**Comment by asterwolf** [comment]
Sorry, I can see that comment coming off as aggressive. It was a serious question, I think every time I put a description of "updating meeting minutes". Lol

**Comment by pathawks** [comment]
I was really referring to the title: **New branch**

You're fine. I just get confused whenever **New branch** pops up in my notifications. 😛

**Comment by asterwolf** [comment]
Oh, so is it based off what I'm naming the branch? Or if no description is provided, it just adds the name or the branch I am merging from? Yeah, once I get more people involved here (and definitely next semester I will), I'll have a lot more descriptions. :p

**Pull request merged**
