### PR TITLE
Inserted audio link at top per amendment motion

### PR DESCRIPTION
**Pull request by ChadH1971**
The link to the audio recording of this is at the top with an annotation of the amendment motion passed on 10/07/16

### CODE REVIEW

**Comment by asterwolf** [comment]
Are you sure you're okay with the way it's displayed? Maybe be a little more clear of what was amended? If you decide you want to make edits to your already existing pull request (do not create a new one), go to files changed tab and from there click the edit button to edit an already existing pull request.

**Comment by ChadH1971** [comment]
I made a small change to the placement and wording to clear up the amended link

**Comment by pathawks** [comment]
Do you really need to "amend" the minutes to include a link like this? _shrug_

**Comment by ChadH1971** [comment]
Since the minutes had been previously adopted, I felt better about annotating the slight change

**Pull request merged**
